### ISSUE TITLE
Incorrectly returns true with strings

### ISSUE THREAD

**Issue by strugee** [Steditor/es7-array.prototype.includes#1]
When examining an array with strings, if `.includes` is passed a string, it incorrectly returns true:

```
% node
> require('es7-array.prototype.includes');
{}
> var arr = ['a', 'b'];
undefined
> arr.includes('c');
true
> 
```

I'm on `es7-array.prototype.includes@1.0.1`, Node 4.4.4.

**Comment by Steditor** [comment]
Thank you for the bug report!
Turns out, during the few days I published this module, there was a error in the MDN-polyfill that caused the algorithm to only work on numbers. (See the [page history](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/includes$history) for details)

I have updated to the current polyfill and now Strings work correctly.

**Comment by strugee** [comment]
:thumbsup: thank you!
